build:
	rlc obfuscator.ref --classic

run:
	./obfuscator config.json

example:
	rlc example.ref && ./example

result:
	rlc result.ref && ./result

clean:
	rm example obfuscator result*

.PHONY: build run example result clean